name: rate_limit
version: 0.1.0
author: Sean Eagan <seaneagan1@gmail.com>
description: Rate limiting for Streams.
homepage: http://github.com/seaneagan/rate_limit
dev_dependencies:
  fake_async: ^0.1.0
  test: ^0.12.0
